---
# This playbook deploys base environment for Openstack Icehouse. 

- hosts: compute_nodes
  user: root
  remote_user: root
  sudo: yes
  roles:
    - ntp-standalone
    - hosts-prep
    - update-kernel-modules